version: '3'

vars:
  DB_URL: "postgres://merch_user:merch_password@localhost:5432/merch_db?sslmode=disable"

tasks:
  migrate-up:
    cmds:
      - go run cmd/migrator/main.go -db "{{.DB_URL}}" -path "./migrations/0001_create_tables" -action up

  migrate-down:
    cmds:
      - go run cmd/migrator/main.go -db "{{.DB_URL}}" -path "./migrations/0001_create_tables" -action down

  docker-build:
    cmds:
      - docker-compose build

  docker-up:
    cmds:
      - docker-compose up -d

  docker-down:
    cmds:
      - docker-compose down

  docker-inspect:
    cmds:
      - docker exec -it merch_store_postgres psql -U merch_user -d merch_db

  run-app:
    dotenv: ['.env']
    cmds:
      - go run ./cmd/merch-store/ --jwt-secret=$JWT_SECRET

  run-test:
    cmds:
      - go test -coverprofile=coverage.out -coverpkg=./internal/... ./internal/...

  run-e2e-test:
    cmds:
      - go test -count=1 ./e2e


  view-test-report:
    cmds:
      - go tool cover -func=coverage.out

  coverage:
    dotenv: ['.env']
    env:
      COVERALLS_TOKEN: $COVERALLS_REPO_TOKEN
    cmds:
      - goveralls -coverprofile=coverage.out

  lint:
    cmds:
      - golangci-lint run --fix

  test-migrate-up:
    cmds:
      - go run cmd/migrator/main.go -db "{{.DB_URL}}" -path "./migrations/0002_initialize_stress_data" -action up

  test-migrate-down:
    cmds:
      - go run cmd/migrator/main.go -db "{{.DB_URL}}" -path "./migrations/0002_initialize_stress_data" -action down

