//go:build !coverage
// +build !coverage

// Code generated by mockery v2.52.1. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// CoinRepo is an autogenerated mock type for the CoinRepo type
type CoinRepo struct {
	mock.Mock
}

// TransferMoney provides a mock function with given fields: to, from, amount
func (_m *CoinRepo) TransferMoney(to string, from string, amount int) error {
	ret := _m.Called(to, from, amount)

	if len(ret) == 0 {
		panic("no return value specified for TransferMoney")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string, string, int) error); ok {
		r0 = rf(to, from, amount)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewCoinRepo creates a new instance of CoinRepo. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewCoinRepo(t interface {
	mock.TestingT
	Cleanup(func())
}) *CoinRepo {
	mock := &CoinRepo{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
