// Code generated by mockery v2.52.1. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// Buyer is an autogenerated mock type for the Buyer type
type Buyer struct {
	mock.Mock
}

// Buy provides a mock function with given fields: username, item
func (_m *Buyer) Buy(username string, item string) error {
	ret := _m.Called(username, item)

	if len(ret) == 0 {
		panic("no return value specified for Buy")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string, string) error); ok {
		r0 = rf(username, item)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewBuyer creates a new instance of Buyer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewBuyer(t interface {
	mock.TestingT
	Cleanup(func())
}) *Buyer {
	mock := &Buyer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
