name: Merch App CI

on: [push, pull_request]

jobs:
  lint:
    name: Run GolangCI-Lint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5.3.0
        with:
          go-version: 1.23.2

      - name: Verify go mod tidy produces no changes
        run: |
          go mod tidy
          git diff --exit-code || (echo "Run 'go mod tidy' and commit changes" && exit 1)

      - name: Run GolangCI-Lint
        uses: golangci/golangci-lint-action@v6.0.1
        with:
          version: v1.54.2
          args: --timeout=5m
